name: Validate Renovate Config

on:
  push:
    paths:
      - '.github/renovate.json5'
  pull_request:
    paths:
      - '.github/renovate.json5'

permissions: read-all

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Validate Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict
